### ISSUE TITLE
Ghost can move UP where they should not be able to

### ISSUE THREAD

**Issue by armin-reichert** [floooh/pacman.c#2]
There are four tiles in the maze where ghosts (who are not dead) cannot move UP thus providing Pac-Man a safe place. This seems not to be implemented.

**Comment by floooh** [comment]
Ah alright! I missed this in the Pacman dossier. Those "red zones" actually explain why Blinky is behaving differently at the start of a round. In my version he's heading upwards at the first intersection to reach his scatter target, but he's actually forbidden to do that on the arcade machine and instead takes the long way around. I'll add those exceptions to the code today.

**Comment by floooh** [comment]
Ah ok, now I know what you mean, shortly pressing the down key *within* the intersection tile. Ok I need to change movement code for Pacman a bit for this, I think it should be enough to do the input test only when Pacman enters a new tile, not at every pixel.

**Comment by armin-reichert** [comment]
In my understanding, the ghosts can travel at these four tiles upwards only when they are dead ("eyes"). This feature is important because it allows Pac-Man to take a safe place under certain conditions.

**Comment by floooh** [comment]
In the Pacman Dossier the two "red zones" (one right above the ghost house, and one in Pacman's starting row) are explained like this:

*The two red zones represent the areas where ghosts are forbidden to make upward turns. Once a ghost enters either of these two zones, it may only travel from right-to-left or left-to-right until exiting the area. Thus, only Pac-Man has access to these four, upward-facing tunnel entrances.*

This makes it sound like ghosts are generally forbidden to move upwards (and this also explains Blinky's behaviour at the start of a round), I have implemented it like explained in the Dossier now, and this fixes Blinky's starting behaviour, it's the same as in the emulator now.

**Comment by floooh** [comment]
(I actually need to add an exception for dead ghosts now...)

**Comment by floooh** [comment]
Ok exception added, also need to update the WASM version...

**Comment by floooh** [comment]
...ok WASM version updated.
