### ISSUE TITLE
Windows 10 - error build

### ISSUE THREAD

**Issue by hbiblia** [floooh/pacman.c#3]
Intente compilar para Windows 10 y ocurrió un error.

![image](https://user-images.githubusercontent.com/1939353/114447811-cbba7800-9ba0-11eb-8eaa-92b4a92da112.png)

Agregando esto al CMakeLists.txt **target_link_libraries(sokol gdi32 ole32 oleaut32)** se resolvió.

https://github.com/hbiblia/pacman.c/blob/main/CMakeLists.txt

**Comment by floooh** [comment]
Hi, what compiler are you using? Maybe GCC on mingw/msys2? 

The sokol headers contain pragma-comment-lib statements for linking:

https://github.com/floooh/sokol/blob/2bd6e83c48a4271042e46cf2ba8eaf64e322092c/sokol_app.h#L1713-L1723

...which is detected by MSVC and Clang, but not GCC.

**Comment by hbiblia** [comment]
Si **mingw/msys2**

Ahora mismo solo me esta obligando colocar **-lgdi32 -lole32** pero no me molesta. 😂
