### ISSUE TITLE
Slightly concerned about the copyright issues

### ISSUE THREAD

**Issue by elliott-wen** [floooh/pacman.c#4]
This project is amazing, I am planing to use it as an education tool for students in my AI classes. 

However, this project seems to be using some copyrighted data, i.e., the rom data dump for the arcade machine. 

This may be a bit problematic. I am working to change the sound tracks and sprites a bit.

**Comment by floooh** [comment]
The easiest way to replace the image data is probably to skip the tile decoding steps which decode the ROM dump tile data into a regular texture where each sprite or tile is a simple rectangle in the texture, and instead directly embed an offline-created tile texture, basically skip these two steps:

https://github.com/floooh/pacman.c/blob/709a31d728032c0c8cc0bdc5d76f12d83bd97644/pacman.c#L2825-L2826

You can find the pixel content of the tiles and sprites here:

http://www.retrogamedeconstructionzone.com/2020/01/graphics-in-early-arcade-games-tilemaps.html

(looking like this:

<img width="692" alt="Screen Shot 2021-07-21 at 11 57 48 AM" src="https://user-images.githubusercontent.com/1699414/126470944-c74308ff-7036-47a8-a99c-9461d8ca209a.png">

...hmm wait, these are only the 8x8 tiles, not the 16x16 sprites. But if you google for "Pacman tile texture" or similar, you should also find the sprites).

...only difference is the layout in the texture. All 256 8x8 tiles are arranged horizontally in a line, and below the 64 16x16 sprite tiles, so the texture's width is 8 * 256 = 2048 pixels, and the height is 8 + 16 = 24 pixels.

Hope this helps :)
