### ISSUE TITLE
Instructions for Linux lack something

### ISSUE THREAD

**Issue by mulle-nat** [floooh/pacman.c#5]
I also needed `libasound2-dev`. 

Also what's the difference between `( cd build ; cmake .. )` and `cmake --build .` ? One seems superflous.

Otherwise, very nice :) 👍

**Comment by floooh** [comment]
Ah thanks, I'll update the build instructions for Linux.

But for cmake:

```cmake ..``` generates the actual build files, while ```cmake --build .``` performs the actual build. When only running ```cmake --build .``` without the first step I get:

```
build ➤ cmake --build ..
Error: could not load cache
build ➤
```

**Comment by floooh** [comment]
Ok: https://github.com/floooh/pacman.c/commit/2419f1a6817c459d63a952c54990eb8dbbe45403

**Comment by mulle-nat** [comment]
Hmm, I learned something new about cmake :)
