### ISSUE TITLE
Pacman animation speed too slow

### ISSUE THREAD

**Issue by MikeDX** [floooh/pacman.c#8]
Comparing the animation speed in pacman.c seems to differ to the original by about 50%.

I propose the fix for this to check for the ticks to be increased from /4 to /2 in `spr_anim_pacman` around line 1139 from

```c
 uint32_t phase = (tick / 4) & 3;
```

to
```c
 uint32_t phase = (tick / 2) & 3;
```

This appears to be much closer to the original.

Happy to submit a PR if you wish :)

**Comment by floooh** [comment]
Hmm, tbh I was just eye-balling it and it might definitely be wrong. Happy to merge a PR :)
